export const data=[
    {
        id:1,
        nameProduct:'Programación básica y avanzada',
        price: 50000,
        urlImage: '/public/images/Programacion_basica_&_avanzada.png',
        quantity: 1,
    },
    {
        id:2,
        nameProduct:'Desarrollo web (HTML, CSS, JavaScript)',
        price: 50000,
        urlImage: '/public/images/Desarrollo_Web.jpg',
        quantity: 1,
    },
    {
        id:3,
        nameProduct:'Desarrollo de aplicaciones móviles (Android, iOS)',
        price: 50000,
        urlImage: '/public/images/Desarollo_Movil.jpg',
        quantity: 1,
    },
    {
        id:4,
        nameProduct:'Bases de datos y SQL',
        price: 50000,
        urlImage: '/public/images/BBDD_&_SQL.png',
        quantity: 1,
    },
    {
        id:5,
        nameProduct:'Ciberseguridad y hacker ético',
        price: 50000,
        urlImage: '/public/images/Hacking-Etico.jpg',
        quantity: 1,
    },
    {
        id:6,
        nameProduct:'Inteligencia artificial y aprendizaje automático',
        price: 50000,
        urlImage: '/public/images/IA_&_Aprendizaje_Automático.jpg',
        quantity: 1,
    },
    {
        id:7,
        nameProduct:'Desarrollo de juegos',
        price: 50000,
        urlImage: '/public/images/Desarrollo_de_juegos.jpg',
        quantity: 1,
    },
    {
        id:8,
        nameProduct:'Internet de las cosas (IoT)',
        price: 50000,
        urlImage: '/public/images/iot.jpg',
        quantity: 1,
    },
    {
        id:9,
        nameProduct:'Análisis de datos y visualización',
        price: 50000,
        urlImage: '/public/images/Análisis_de_datos_&_visualización.jpg',
        quantity: 1,
    },
    {
        id:10,
        nameProduct:'Cloud computing (computación en la nube)',
        price: 50000,
        urlImage: '/public/images/Cloud_computing.png',
        quantity: 1,
    },
    {
        id:11,
        nameProduct:'Desarrollo de software con metodologías ágiles',
        price: 50000,
        urlImage: '/public/images/Metodologias_agiles.jpg',
        quantity: 1,
    },
    {
        id:12,
        nameProduct:'Blockchain y criptomonedas',
        price: 50000,
        urlImage: '/public/images/Blockchain_&_criptomonedas.jpg',
        quantity: 1,
    },
    {
        id:13,
        nameProduct:'Diseño de interfaces de usuario (UI/UX)',
        price: 50000,
        urlImage: '/public/images/UI&UX.png',
        quantity: 1,
    },
    {
        id:14,
        nameProduct:'Realidad virtual y aumentada',
        price: 50000,
        urlImage: '/public/images/Realidad_virtual_&_aumentada.jpg',
        quantity: 1,
    },
    {
        id:15,
        nameProduct:'Administración de sistemas y redes',
        price: 50000,
        urlImage: '/public/images/Administración_de_sistemas_&_redes.jpg',
        quantity: 1,
    }
]
       